spring:
  application:
    name: BookExplorer

  datasource:
    url: jdbc:postgresql://localhost:5432/bookexplorer
    username: "myuser"
    password: "secret"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  graphql:
    graphiql:
      enabled: true

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # 24 hrs

logging:
  level:
    root: INFO
    com.nineleaps.BookExplorer: DEBUG
    org.springframework.graphql: DEBUG

  file:
    name: logs/book-explorer.log

server:
  port: 8080

